name: qamr-crs
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
      - --extra-index-url https://download.pytorch.org/whl/cu128
      - torch==2.7.0+cu128
      - torch-geometric==2.8.0
      - transformers==4.37.2
      - tokenizers==0.15.2
      - accelerate==1.14.0
      - numpy==2.2.6
      - scipy==1.15.3
      - scikit-learn==1.7.2
      - wandb==0.17.9
      - loguru
      - nltk
      - tqdm
